export const coinNames = [
  "Bitcoin",
  "Ethereum",
  "Tether USD",
  "HEX",
  "Binance Coin",
  "Cardano",
  "Solana",
  "Polkadot",
  "XRP",
  "SHIBA INU",
  "Terra",
  "Dogecoin",
  "USDC",
  "Uniswap",
  "Avalanche",
  "Chainlink",
  "Wrapped BTC",
  "Binance USD",
  "Litecoin",
  "Polygon",
  "Cosmos",
  "Bitcoin Cash",
  "Algorand",
  "VeChain",
  "Dai",
  "Axie Infinity",
  "Internet Computer (DFINITY)",
  "PancakeSwap",
  "FTX Token",
  "Stellar",
  "Theta Token",
  "Compound Ether",
  "OKB",
  "TRON",
  "Ethereum Classic",
  "Tezos",
  "Filecoin",
  "Monero",
  "Aave",
  "Elrond",
  "Crypto.com Chain",
  "EOS",
  "Compound Dai",
  "1inch Token",
  "Wootrade",
  "Hedera HashGraph",
  "Klaytn",
  "NEAR Protocol",
  "Olympus",
  "IOTA",
  "SafeMoon",
  "eCash",
  "Kusama",
  "LEO",
  "THORChain",
  "AMP",
  "Waves",
  "Bitcoin SV",
  "Celsius Network",
  "MobileCoin",
  "NEO",
  "The Graph",
  "Quant",
  "Lido DAO Token",
  "SUSHI",
  "Helium",
  "Huobi BTC",
  "BitTorrent",
  "Maker",
  "Luxurious Pro Network Token",
  "Arweave",
  "TerraUSD",
  "One",
  "Content Value Network",
  "Zcash",
  "Compound",
  "Holo",
  "Curve DAO Token",
  "Dash",
  "OMG Network",
  "Chiliz",
  "Nexo",
  "Blockstack",
  "Synthetix Network",
  "Decentraland",
  "Theta Fuel",
  "Enjin Coin",
  "Decred",
  "Huobi Token",
  "SKALE",
  "Elitium",
  "yearn.finance",
  "The Transfer Token",
  "QTUM",
  "Zilliqa",
  "KuCoin Token",
  "WAX Economic Token",
  "Rally",
  "XinFin Network",
  "ECOMI"
]